当异常发生在析构函数中，岂不是要gg?

有两种做法:
    如果是发生异常，就让程序终止，那么一般会这样:
        B:~B()
        {
            try{
                db.close();
               }catch(...){
                   std::abort();
            } 
        }

    这样只是告诉有错误，并没有捕捉错误的机会，现在如果有捕捉错误的机会就好了，那么就必须通知客户有错误才行，一般这样:
        class Dec{
            public:
            void close()
            {
                db.close();
                closed = true;
            }
            ~Dec(){
                if(!closed){
                    tyr{
                        db.close();
                    }catch(...){
                        //进行操作
                    }
                }
            }
            private:
            DBconnetion db;
            bool closed;
        }
    这样closed相当于晴雨表。
